#!/bin/bash
# =============================================================================
# EC2-native PQC SSH honeypot -- provisioning (Ubuntu, cloud-init user_data)
# =============================================================================
# Production form of pqc-poc/ (the Docker PoC). Stands up a *dedicated*
# observation sshd on port 2223 that advertises a post-quantum key exchange and
# logs which kex each attacker's client negotiates -- the same kex_negotiated
# JSON signal the PoC emits -- without touching the admin sshd on port 22.
#
# Mirrors terraform/modules/aws-ec2/user_data.sh conventions (apt-get, echo
# progress, || true) and pqc-poc/entrypoint.sh's kex-parsing logic verbatim so
# the two deployments produce byte-identical events into honeypot-* / CloudWatch.
#
# Append this to the EC2 module's user_data.sh, or run standalone on any Ubuntu
# host. Auth always fails (no accounts) -- this variant only observes the
# handshake. Credential capture + Cowrie hand-off is the separate Docker relay
# (see pqc-poc/handoff/); pure non-hybrid pqc-only needs OQS-OpenSSH and is out
# of scope for stock OpenSSH.
#
# OpenSSH-version reality (auto-handled below via `ssh -Q kex`):
#   - Ubuntu 22.04 (jammy) ships OpenSSH 8.9  -> sntrup761x25519-sha512@openssh.com
#     is present and IS post-quantum (NTRU Prime + X25519). No ML-KEM.
#   - ML-KEM hybrid (mlkem768x25519-sha256) needs OpenSSH >= 9.9 -- added only if
#     the installed sshd actually lists it, because sshd REFUSES TO START on an
#     unknown KexAlgorithms entry.
# =============================================================================
set -euo pipefail

PORT=2223
LOGDIR=/var/log/pqc-honeypot
LOGFILE="${LOGDIR}/events.json"
CONF=/etc/ssh/sshd_config.pqc-honeypot
KEYDIR=/etc/ssh/pqc-keys
RUNNER=/usr/local/bin/pqc-honeypot-run.sh

echo "PQC honeypot: provisioning on $(date)"

apt-get update
apt-get install -y openssh-server openssh-client

mkdir -p "$LOGDIR" "$KEYDIR"

# Dedicated host key (kept apart from the admin sshd's keys).
if [ ! -f "$KEYDIR/ssh_host_ed25519_key" ]; then
    ssh-keygen -t ed25519 -f "$KEYDIR/ssh_host_ed25519_key" -N "" -C "pqc-honeypot" >/dev/null
fi
chmod 600 "$KEYDIR/ssh_host_ed25519_key"

# ---------------------------------------------------------------------------
# Build the KexAlgorithms list from what THIS sshd actually supports. Always
# include sntrup761 (PQC, present since 8.5); add ML-KEM only if listed.
# ---------------------------------------------------------------------------
SUPPORTED_KEX="$(ssh -Q kex 2>/dev/null || true)"
KEX_LIST="sntrup761x25519-sha512@openssh.com"
if printf '%s\n' "$SUPPORTED_KEX" | grep -q '^mlkem768x25519-sha256$'; then
    KEX_LIST="mlkem768x25519-sha256,${KEX_LIST}"
    echo "PQC honeypot: ML-KEM hybrid supported -> advertising mlkem768x25519-sha256"
else
    echo "PQC honeypot: no ML-KEM on this OpenSSH (need >= 9.9) -> sntrup761 only"
fi
echo "PQC honeypot: KexAlgorithms = ${KEX_LIST}"

# ---------------------------------------------------------------------------
# Honeypot sshd config: observation-only, hardened, LogLevel DEBUG1 so the
# "kex: algorithm:" line is emitted for the parser. No accounts => auth fails;
# the kex is negotiated pre-auth, which is all we record.
# ---------------------------------------------------------------------------
cat > "$CONF" <<EOF
# PQC SSH honeypot -- generated by user_data.pqc.sh. Observation only.
Port ${PORT}
ListenAddress 0.0.0.0
Protocol 2

HostKey ${KEYDIR}/ssh_host_ed25519_key

# The point of the honeypot: advertise a post-quantum key exchange.
KexAlgorithms ${KEX_LIST}

# Log the negotiated kex (debug1: kex: algorithm: ...).
LogLevel DEBUG1

# No real access -- containment. Auth is irrelevant; kex logs pre-auth.
PermitRootLogin no
PasswordAuthentication yes
PubkeyAuthentication no
PermitEmptyPasswords no
AuthenticationMethods password
MaxAuthTries 3

AllowTcpForwarding no
X11Forwarding no
PermitTunnel no
AllowAgentForwarding no
PermitUserEnvironment no
UsePAM no
Subsystem sftp /bin/false
EOF

# Validate before we install the service (sshd -t refuses unknown kex names).
/usr/sbin/sshd -t -f "$CONF"

# ---------------------------------------------------------------------------
# Runner: identical kex-parsing to pqc-poc/entrypoint.sh, adapted to bash.
# Runs sshd in the foreground and turns each negotiated-kex line into JSON.
# ---------------------------------------------------------------------------
cat > "$RUNNER" <<'EOF'
#!/bin/bash
set -euo pipefail
CONF=/etc/ssh/sshd_config.pqc-honeypot
LOGDIR=/var/log/pqc-honeypot
LOGFILE="${LOGDIR}/events.json"
mkdir -p "$LOGDIR"

emit() { printf '%s\n' "$1" | tee -a "$LOGFILE"; }

port=$(awk '/^Port /{print $2; exit}' "$CONF")
emit "{\"event\":\"honeypot_start\",\"variant\":\"ec2-hybrid\",\"port\":${port:-0}}"

# -D foreground, -e log to stderr; fold stderr into the pipe and parse it.
/usr/sbin/sshd -D -e -f "$CONF" 2>&1 | while IFS= read -r line; do
    printf '%s\n' "$line" >&2          # keep the raw sshd line for forensics
    case "$line" in
        *"kex: algorithm:"*)
            kex=${line##*kex: algorithm: }
            kex=${kex%% *}
            case "$kex" in
                *mlkem*|*sntrup*|*kyber*) pq=true ;;
                *)                        pq=false ;;
            esac
            emit "{\"event\":\"kex_negotiated\",\"variant\":\"ec2-hybrid\",\"kex_algorithm\":\"${kex}\",\"post_quantum\":${pq}}"
            ;;
    esac
done
EOF
chmod 755 "$RUNNER"

# ---------------------------------------------------------------------------
# systemd unit -- keeps the observation sshd running, restarts on failure.
# ---------------------------------------------------------------------------
cat > /etc/systemd/system/pqc-honeypot.service <<EOF
[Unit]
Description=PQC SSH honeypot (observation-only, port ${PORT})
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${RUNNER}
Restart=always
RestartSec=2
# Containment: no new privileges, minimal writable paths.
NoNewPrivileges=true
ProtectHome=true
ProtectSystem=strict
ReadWritePaths=${LOGDIR}

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now pqc-honeypot.service

echo "PQC honeypot: listening on ${PORT}; events -> ${LOGFILE} on $(date)"
