#!/usr/bin/env python3

################################################################################
# Automated Reports Generation Script
# Generates daily/weekly/monthly attack reports as HTML and JSON.
#
# The Elasticsearch aggregations live in honeypot_stats.py, shared with
# generate-pdf-report.py and generate-analytics-report.py. Email delivery lives
# in notifiers.py.
################################################################################

import argparse
import html
import json
import os
import sys
from datetime import datetime
from typing import Any, Dict

from honeypot_stats import HoneypotStats
from notifiers import EmailNotifier, NotificationError

REPORT_DIR = os.getenv("REPORT_OUTPUT_DIR", "/tmp")

PERIODS = {
    "daily": ("24h", "last 24 hours"),
    "weekly": ("7d", "last 7 days"),
    "monthly": ("30d", "last 30 days"),
}


def _rows(pairs, columns) -> str:
    """Table rows from an iterable of tuples, every cell escaped."""
    if not pairs:
        return f'<tr><td colspan="{columns}" class="empty">Nothing recorded in this period</td></tr>'
    return "".join(
        "<tr>" + "".join(f"<td>{html.escape(str(cell))}</td>" for cell in row) + "</tr>"
        for row in pairs
    )


def render_html(stats: Dict[str, Any], label: str) -> str:
    """Render the report.

    Values come from honeypot traffic, so every one of them is escaped -- an
    attacker picks their own source IP, username and command strings, and this
    report gets opened in a browser and mailed to an operator.
    """
    top_ips = [(ip["ip"], ip["count"]) for ip in stats["top_ips"]]
    services = [(s["name"], s["count"], f"{s['percentage']}%") for s in stats["service_breakdown"]]
    countries = list(stats["countries"].items())

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Honeypot attack report</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin: 24px; background: #f5f5f5; color: #222; }}
  .header {{ background: #23303a; color: #fff; padding: 20px; border-radius: 4px; }}
  .header h1 {{ margin: 0 0 6px; font-size: 20px; }}
  .header p {{ margin: 0; opacity: .75; font-size: 13px; }}
  .section {{ background: #fff; margin: 18px 0; padding: 18px; border-radius: 4px; border: 1px solid #e2e2e2; }}
  .section h2 {{ margin: 0 0 14px; font-size: 15px; }}
  .metrics {{ display: flex; flex-wrap: wrap; gap: 12px; }}
  .metric {{ flex: 1 1 160px; padding: 14px; background: #f7f8f9; border-radius: 4px; }}
  .metric .value {{ font-size: 26px; font-weight: 600; }}
  .metric .label {{ color: #6b7280; font-size: 12px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th, td {{ padding: 8px 10px; text-align: left; border-bottom: 1px solid #eee; }}
  th {{ background: #f0f2f4; font-size: 12px; }}
  td.empty {{ color: #6b7280; font-style: italic; }}
  .footer {{ color: #6b7280; font-size: 11px; text-align: center; margin-top: 28px; }}
</style>
</head>
<body>
  <div class="header">
    <h1>Honeypot attack report</h1>
    <p>Period: {html.escape(label)} &middot; Generated {datetime.now():%Y-%m-%d %H:%M:%S}</p>
  </div>

  <div class="section">
    <h2>Summary</h2>
    <div class="metrics">
      <div class="metric"><div class="value">{stats['total_events']:,}</div><div class="label">Total events</div></div>
      <div class="metric"><div class="value">{stats['unique_source_ips']}</div><div class="label">Source addresses</div></div>
      <div class="metric"><div class="value">{stats['failed_logins']:,}</div><div class="label">Failed logins</div></div>
      <div class="metric"><div class="value">{stats['credentials_captured']:,}</div><div class="label">Credentials captured</div></div>
    </div>
  </div>

  <div class="section">
    <h2>Top source addresses</h2>
    <table><tr><th>IP address</th><th>Events</th></tr>{_rows(top_ips, 2)}</table>
  </div>

  <div class="section">
    <h2>Targeted services</h2>
    <table><tr><th>Service</th><th>Events</th><th>Share</th></tr>{_rows(services, 3)}</table>
  </div>

  <div class="section">
    <h2>Source countries</h2>
    <table><tr><th>Country</th><th>Events</th></tr>{_rows(countries, 2)}</table>
  </div>

  <div class="footer">
    Generated by the Honeypot Framework &middot;
    https://github.com/Sickwoman/honeypot-framework
  </div>
</body>
</html>"""


def save(content: str, name: str, extension: str) -> str:
    path = os.path.join(REPORT_DIR, f"honeypot-{name}-{datetime.now():%Y%m%d_%H%M%S}.{extension}")
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)
    print(f"✓ Wrote {path}")
    return path


def generate(report_type: str, email_to: str = None) -> None:
    period, label = PERIODS[report_type]
    print(f"Generating {report_type} report ({label})...")

    stats = HoneypotStats().summary(period)
    document = render_html(stats, label)

    save(document, report_type, "html")
    save(json.dumps({"generated": datetime.now().isoformat(), **stats}, indent=2), report_type, "json")

    recipient = email_to or os.getenv("REPORT_EMAIL_TO")
    if not recipient:
        return
    try:
        notifier = EmailNotifier()
        subject = f"Honeypot {report_type} report"
        print("✓ Emailed report" if notifier.send_html(recipient, subject, document)
              else "✗ Report email failed")
    except NotificationError as exc:
        print(f"✗ Not emailing the report: {exc}", file=sys.stderr)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate honeypot attack reports")
    parser.add_argument("type", choices=[*PERIODS, "all"], help="Reporting period")
    parser.add_argument("--email-to", help="Send the HTML report here (default: $REPORT_EMAIL_TO)")
    args = parser.parse_args()

    for report_type in (PERIODS if args.type == "all" else [args.type]):
        generate(report_type, args.email_to)
    return 0


if __name__ == "__main__":
    sys.exit(main())
