#!/usr/bin/env python3

################################################################################
# Alert Notifications & Webhooks Integration
# Send alerts to Slack, Discord, Email, and custom webhooks
################################################################################

import requests
import json
import os
from datetime import datetime
from enum import Enum

class AlertLevel(Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"

class AlertNotifier:
    def __init__(self):
        self.slack_webhook = os.getenv('SLACK_WEBHOOK_URL')
        self.discord_webhook = os.getenv('DISCORD_WEBHOOK_URL')
        self.email_to = os.getenv('ALERT_EMAIL_TO')
        self.custom_webhook = os.getenv('CUSTOM_WEBHOOK_URL')
    
    def send_slack_alert(self, title, message, level=AlertLevel.INFO):
        """Send alert to Slack"""
        if not self.slack_webhook:
            print("❌ Slack webhook not configured")
            return False
        
        color_map = {
            AlertLevel.INFO: "#36a64f",
            AlertLevel.WARNING: "#ff9900",
            AlertLevel.CRITICAL: "#ff0000"
        }
        
        payload = {
            "attachments": [
                {
                    "fallback": title,
                    "color": color_map.get(level, "#36a64f"),
                    "title": f"🍯 {title}",
                    "text": message,
                    "footer": "Honeypot Framework",
                    "ts": int(datetime.now().timestamp())
                }
            ]
        }
        
        try:
            response = requests.post(self.slack_webhook, json=payload)
            if response.status_code == 200:
                print(f"✅ Slack alert sent: {title}")
                return True
            else:
                print(f"❌ Slack error: {response.status_code}")
                return False
        except Exception as e:
            print(f"❌ Error sending Slack alert: {e}")
            return False
    
    def send_discord_alert(self, title, message, level=AlertLevel.INFO):
        """Send alert to Discord"""
        if not self.discord_webhook:
            print("❌ Discord webhook not configured")
            return False
        
        color_map = {
            AlertLevel.INFO: 0x36a64f,
            AlertLevel.WARNING: 0xff9900,
            AlertLevel.CRITICAL: 0xff0000
        }
        
        payload = {
            "embeds": [
                {
                    "title": f"🍯 {title}",
                    "description": message,
                    "color": color_map.get(level, 0x36a64f),
                    "timestamp": datetime.now().isoformat(),
                    "footer": {
                        "text": "Honeypot Framework"
                    }
                }
            ]
        }
        
        try:
            response = requests.post(self.discord_webhook, json=payload)
            if response.status_code == 204:
                print(f"✅ Discord alert sent: {title}")
                return True
            else:
                print(f"❌ Discord error: {response.status_code}")
                return False
        except Exception as e:
            print(f"❌ Error sending Discord alert: {e}")
            return False
    
    def send_email_alert(self, subject, message, level=AlertLevel.INFO):
        """Send alert via email"""
        if not self.email_to:
            print("❌ Email not configured")
            return False
        
        try:
            import smtplib
            from email.mime.text import MIMEText
            from email.mime.multipart import MIMEMultipart
            
            sender = os.getenv('ALERT_EMAIL_FROM', 'honeypot@example.com')
            password = os.getenv('ALERT_EMAIL_PASSWORD', '')
            smtp_server = os.getenv('ALERT_SMTP_SERVER', 'smtp.gmail.com')
            smtp_port = int(os.getenv('ALERT_SMTP_PORT', '587'))
            
            msg = MIMEMultipart()
            msg['Subject'] = f"[{level.value.upper()}] {subject}"
            msg['From'] = sender
            msg['To'] = self.email_to
            
            body = f"""
            <html>
            <body style="font-family: Arial, sans-serif;">
                <h2 style="color: {'green' if level == AlertLevel.INFO else 'orange' if level == AlertLevel.WARNING else 'red'};">
                    🍯 Honeypot Alert
                </h2>
                <p><strong>Level:</strong> {level.value.upper()}</p>
                <p><strong>Time:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                <hr>
                <p>{message}</p>
                <hr>
                <p style="color: #888; font-size: 12px;">
                    This alert was generated by Honeypot Framework
                </p>
            </body>
            </html>
            """
            
            msg.attach(MIMEText(body, 'html'))
            
            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()
                server.login(sender, password)
                server.send_message(msg)
            
            print(f"✅ Email alert sent to {self.email_to}")
            return True
        except Exception as e:
            print(f"❌ Error sending email: {e}")
            return False
    
    def send_webhook_alert(self, event_type, data, level=AlertLevel.INFO):
        """Send alert to custom webhook"""
        if not self.custom_webhook:
            print("❌ Custom webhook not configured")
            return False
        
        payload = {
            "event_type": event_type,
            "level": level.value,
            "timestamp": datetime.now().isoformat(),
            "data": data
        }
        
        try:
            response = requests.post(self.custom_webhook, json=payload)
            if response.status_code in [200, 201, 204]:
                print(f"✅ Webhook alert sent: {event_type}")
                return True
            else:
                print(f"❌ Webhook error: {response.status_code}")
                return False
        except Exception as e:
            print(f"❌ Error sending webhook: {e}")
            return False
    
    def send_all_alerts(self, title, message, level=AlertLevel.INFO):
        """Send alert to all configured channels"""
        print(f"\n📢 Sending alerts: {title}")
        print(f"   Level: {level.value}")
        
        self.send_slack_alert(title, message, level)
        self.send_discord_alert(title, message, level)
        self.send_email_alert(title, message, level)
        self.send_webhook_alert("honeypot_alert", {
            "title": title,
            "message": message
        }, level)

# Alert Types
class AlertTypes:
    HIGH_ATTACK_VOLUME = "High Attack Volume Detected"
    MALWARE_DETECTED = "Malware Download Attempt"
    BRUTE_FORCE = "Brute Force Attack Detected"
    PORT_SCAN = "Port Scan Detected"
    CREDENTIAL_CAPTURE = "Credentials Captured"
    SERVICE_DOWN = "Service Down"
    HIGH_MEMORY = "High Memory Usage"
    DISK_FULL = "Disk Space Low"

def monitor_and_alert():
    """Monitor honeypot and send alerts"""
    import requests
    
    notifier = AlertNotifier()
    es_url = "https://localhost:9200"
    username = "elastic"
    password = os.getenv('ELASTICSEARCH_PASSWORD', 'changeme')
    
    try:
        # Check for high attack volume (100+ in 5 minutes)
        response = requests.get(
            f"{es_url}/honeypot-*/_count",
            auth=(username, password),
            verify=False,
            json={
                "query": {
                    "range": {
                        "@timestamp": {"gte": "now-5m"}
                    }
                }
            }
        )
        
        count = response.json().get('count', 0)
        if count > 100:
            notifier.send_all_alerts(
                AlertTypes.HIGH_ATTACK_VOLUME,
                f"{count} attacks detected in the last 5 minutes",
                AlertLevel.CRITICAL
            )
        
        # Check for malware attempts
        response = requests.get(
            f"{es_url}/honeypot-*/_count",
            auth=(username, password),
            verify=False,
            json={
                "query": {
                    "bool": {
                        "must": [
                            {"match": {"logdata.CMD": "wget"}},
                            {"range": {"@timestamp": {"gte": "now-1h"}}}
                        ]
                    }
                }
            }
        )
        
        malware_count = response.json().get('count', 0)
        if malware_count > 0:
            notifier.send_all_alerts(
                AlertTypes.MALWARE_DETECTED,
                f"{malware_count} malware download attempts detected",
                AlertLevel.CRITICAL
            )
    
    except Exception as e:
        print(f"❌ Monitoring error: {e}")

if __name__ == "__main__":
    import sys
    
    notifier = AlertNotifier()
    
    if len(sys.argv) < 2:
        print("Usage: notify-alerts.py [slack|discord|email|webhook|all|monitor]")
        sys.exit(1)
    
    action = sys.argv[1]
    
    if action == "monitor":
        monitor_and_alert()
    elif action == "all":
        notifier.send_all_alerts(
            "Test Alert",
            "This is a test alert from Honeypot Framework",
            AlertLevel.INFO
        )
    else:
        print("Running alert test...")
        notifier.send_all_alerts(
            "Honeypot Alert Test",
            "Test message from notification system",
            AlertLevel.INFO
        )

